---
galaxy_info:
  author: Andrew Rothstein
  description: installs Anaconda
  company: BlackRock
  license:
    - MIT
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Archlinux
      versions:
        - all
  galaxy_tags:
    - python
    - conda
    - anaconda

dependencies:
  - src: andrewrothstein.bash
    version: v1.1.0
  - src: andrewrothstein.unarchive-deps
    version: v1.0.9
