server:
  port: 8081

spring:
  application:
    name: ChatBotApp

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

security:
  enabled: false
